package src.limit.token;

public enum TokenType
{
	T_UNSPECIFIED, T_NUMBER, T_STRING_LITERAL, T_IDENTIFIER, T_CLASS, T_NEW, T_THIS, T_PRINT, T_LET,
	T_VAR, T_SUBST, T_INTO, T_TRUE, T_FALSE, T_EXIT, T_WHITESPACE;
}